export const textFiles = [
  { label: "Caesar Gallic Wars Book 1", value: "caesar_gall1.txt" },
  { label: "Caesar Gallic Wars Book 2", value: "caesar_gall2.txt" },
  { label: "Caesar Civil Wars Book 1", value: "caesar_bc1.txt" },
  { label: "Catullus", value: "catullus.txt" },
  { label: "Lucan Pharsalia Book 1", value: "lucan_lucan1.txt" },
  { label: "Vergil Aeneid Book 1", value: "vergil_aen1.txt" },
  { label: "Vergil Aeneid Book 2", value: "vergil_aen2.txt" },
  { label: "Vergil Aeneid Book 3", value: "vergil_aen3.txt" },
  { label: "Vergil Aeneid Book 4", value: "vergil_aen4.txt" },
  { label: "Vergil Aeneid Book 5", value: "vergil_aen5.txt" },
  { label: "Vergil Aeneid Book 6", value: "vergil_aen6.txt" },
  { label: "Vergil Aeneid Book 7", value: "vergil_aen7.txt" },
  { label: "Vergil Aeneid Book 8", value: "vergil_aen8.txt" },
  { label: "Vergil Aeneid Book 9", value: "vergil_aen9.txt" },
  { label: "Vergil Aeneid Book 10", value: "vergil_aen10.txt" },
  { label: "Vergil Aeneid Book 11", value: "vergil_aen11.txt" },
  { label: "Vergil Aeneid Book 12", value: "vergil_aen12.txt" },
  { label: "Vergil Georgics Book 1", value: "vergil_geo1.txt" },
  { label: "Vergil Georgics Book 2", value: "vergil_geo2.txt" },
  { label: "Vergil Georgics Book 3", value: "vergil_geo3.txt" },
  { label: "Vergil Georgics Book 4", value: "vergil_geo4.txt" },
  { label: "Ovid Amores Book 1", value: "ovid_ovid.amor1.txt" },
  { label: "Ovid Amores Book 2", value: "ovid_ovid.amor2.txt" },
  { label: "Ovid Amores Book 3", value: "ovid_ovid.amor3.txt" },
  { label: "Ovid Heroides 1 - Penelope to Ulysses", value: "ovid_ovid.her1.txt" },
  { label: "Ovid Heroides 2 - Phyllis to Demophoon", value: "ovid_ovid.her2.txt" },
  { label: "Ovid Heroides 3 - Briseis to Achilles", value: "ovid_ovid.her3.txt" },
  { label: "Ovid Heroides 4 - Phyllis to Hippolytus", value: "ovid_ovid.her4.txt" },
  { label: "Ovid Heroides 5 - Oenone to Paris", value: "ovid_ovid.her5.txt" },
  { label: "Ovid Heroides 6 - Hypsipyle to Jason", value: "ovid_ovid.her6.txt" },
  { label: "Ovid Heroides 7 - Dido to Aeneas", value: "ovid_ovid.her7.txt" },
  { label: "Ovid Heroides 10 - Ariadne to Theseus", value: "ovid_ovid.her10.txt" },
  { label: "Ovid Heroides 12 - Medea to Jason", value: "ovid_ovid.her12.txt" },
];
